### ISSUE TITLE
raspbian jessie read-only with desktop environment

### ISSUE THREAD

**Issue by pete111** [hyperion-project/hyperion#601]
Hello, I followed read-only tutorial at https://github.com/hyperion-project/hyperion/wiki/Make-Raspbian-Read-Only. for my Raspbian Jessie. But I need to make it working with dektop environment (standard startx, it automatically logs me in). Any idea what change to make it working?

thanks.

**Comment by tpmodding** [comment]
dont know if i get it, but the option you search is in "sudo raspi-config" then the "3 Enable Boot to Desktop/Scratch" option?

**Comment by pete111** [comment]
@tpmodding, you are talking about option to boot into desktop automatically. But I am talking about making full Raspbian read-only with desktop. Posted article talked about making Raspbian read-only but without desktop. Desktop environment needs some folders writtable so article needs some updates to make it working with it.

**Comment by brindosch** [comment]
This is documentation is now removed, due to the point it have nothing to do with hyperion (cleanup)

Hyperion have a new home!
Please read the announcement post and the changelog for V1.02.0
www.hyperion-project.org

Please have a look at our new wiki! (EN/DE)
wiki.hyperion-project.org

All discussions/questions/development threads should be moved to the new forum!
We will close this issue now
