### ISSUE TITLE
[amlogic] Publish build for amlogic platform

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion#616]
@redPanther 
I noticed you added a amlogic grabber. How stable is this implementation? Which devices are compatible? We may consider to extend the crosscompiler support to publish .tar.gz for these devices.

Users
We need feedback from amlogic owners if the amlogic grabber is working or not. Please post some feedback.

Thank you

**Comment by redPanther** [comment]
Hi,
I'm not added the amlogic grabber. This grabber was already implemented. I made it available as  standalone app.

The implentantion is same as hyperion-v4l2.
Amlogic is used mainly for wetek system.
Ciao

**Comment by brindosch** [comment]
Thank you for clarification. We should gather some information if this runs on other amlogic devices too.

**Comment by redPanther** [comment]
Nice thing is you can send a proto stream from your wetek box to another hyperiond on e.g. a raspi ...

**Comment by certxbmc** [comment]
can i run hyperion on odroid c2?

**Comment by brindosch** [comment]
Hello @certxbmc 
please try out our install script. the wetek build is a amlogic enabled build.
Please report back :) We don´t get much feedback for amlogic devies - no idea

**Comment by alex240188** [comment]
I'm planning to experiment with the odroid c2.
I've already experimented with another amlogic s905 box and I'm pretty sure that the answer is,
No the pre-built binaries will not work on the c2 because the aml grabber has kernel headers copied from codesnakes 3.10 kernel.
Some of these headers have different values on the s905's 3.14 kernel

**Comment by brindosch** [comment]
We create new builds via a crosscompile VM, this wetek (amlogic) build seams to use the Pi dependencies. This may be part of the root problem here.

It is possible to extend the aml grabber or to rework it. If it is still compatible after that with wetek.
also it is possible to extend the crosscompile with amlogic sources for a proper compile.

If you have knowledge or you find a way, just commit a pull request or deliver the sources for a proper crosscompile (if this fixes it). To add a proper support for this devices :)

**Comment by alex240188** [comment]
We have it partially working on the odroid c2 now.
As it's a relatively new soc there are issues where it was necessary to determine if it's the issue of the device or Hyperion.
We can capture with the framegrabber in menus
We can capture h264 using the aml grabber
H265 content is not captured at all.
The border detector changes a few times then gives up with all h265 content

**Comment by alex240188** [comment]
Dmesg is showing that the internal videocap device is capturing at the correct resolutions for the h265 video I am playing so I'm thinking the issue is in Hyperion somewhere

**Comment by brindosch** [comment]
moved more or less to hyperion.ng

**Comment by alorbach** [comment]
Has this issue being adressed in hyperion.ng yet?

**Comment by redPanther** [comment]
The issue with kernel headers should be resolved in ng. But you have to build on your owen. We have no aml build infrastrucrure yet.

**Comment by alorbach** [comment]
Can you point me to the issue in the new code? 
Maybe it is possible to solve the issue in the current hyperion build, I would be able to add the changes and compile the code myself.

**Comment by redPanther** [comment]
look at https://github.com/hyperion-project/hyperion.ng/pull/267 
optional to 348 and 412

the trick is, that we use the system h file instead of copying code into our own code

**Comment by alorbach** [comment]
I am sorry to comment again. The current version of Hyperion in Libreelec is showing WHITE LEDs on H265 content now, not green anymore. 

Is the H265 video content issue fixed in hyperion.ng? 
If yes I would spend time in trying to get a hyperion.ng package for Libreelec instead of trying to backport patches from hyperion.ng.

**Comment by redPanther** [comment]
I've got a odroid c2 about some weeks ago and I reimplementing the whole amlogic stuff. The sittuation for capturing on amlogic platform is very bad, because there is no official supported and flawlessly working method to capture hw accelerated video (not hw accelerated stuff is done by framebuffer).
I never got the current method via /dev/amvideocap working so I searched for other methods. I found some promising kernel patches from crashOverride and now implementing the whole stuff. The downside of this is that you need a self compiled kernel - but on ubuntu for odroid you need it anyway, because aml capture is deactivated. As I read the whole story right there is/was some issues in the amvideocap kernel module (at least I have big issues with that thingy).

more on this topic https://forum.odroid.com/viewtopic.php?f=136&t=20901

**Comment by redPanther** [comment]
Just a note, with move to qt5 in hyperion.ng we lost all our crossplatform toolchains, so currently we are not able to provide reliable binaries. Everybody is welcome to repair our rpi/aml crossplatform toolchain, so we are able to provide bins.

**Comment by alorbach** [comment]
fyi: The problem was fixed setting kernel variables mentioned in this issue: 
https://github.com/hyperion-project/hyperion.ng/issues/470
