### ISSUE TITLE
Commercial takeover and removing wiki pages to forward to commercial site

### ISSUE THREAD

**Issue by Tester0815** [hyperion-project/hyperion#656]
Recover the old pages and don't delete the github pages !
You want to make business, then do it with your own ressources.

**Comment by RickDB** [comment]
Don't know what you're getting at but we moved to a dedicated server for forums which includes an integrated wiki to give the best and most accurate information instead of the old wiki which was outdated and obscure with lack of features or structure.

We are and always will be open source and everyone is free to contribute, feedback is always welcome however don't get what you mean by "own resources" as we use the same information only updated and improved with less misinformation.

**Comment by tpmodding** [comment]
And everything is in agreement with tvdzwan, we ask him by every big step, if he dont want it, we dont do it :)

Have a nice day!

PS: it is github (non-commercial open-source) you can always use old commits if updates and bugfixes "commercial" for you

Cheers

**Comment by Tester0815** [comment]
Bullshit.

The commercial wiki is worse than before.
The structure is completey shit.

The information are not even containing the old pages informations.

Yes, sure you need public coders hold up the status, 
so you benefit without paying from external coders.

**Comment by tpmodding** [comment]
Can you show me examples why the structure is completey shit? May we can update it.
Which informations do you miss from the old pages? Without examples your statements are meaningless and more like trolling...

**Comment by NicoHood** [comment]
I also think the old wiki was better, as you can just edit the pages via github and it just "works". A simple restructure of the github wiki could have done it. However that decision is up to the new maintainers and I am very happy about their effort.

**Comment by tdhz77** [comment]
It's complete shit. Keep it standard or I will fork you.

**Comment by tpmodding** [comment]
Feel free to fork everything you want :)

**Comment by tdhz77** [comment]
<3
