### ISSUE TITLE
Be aware ! Every contribution is a support to the commercialized project

### ISSUE THREAD

**Issue by Tester0815** [hyperion-project/hyperion#657]

**Comment by ntim** [comment]
?

**Comment by tpmodding** [comment]
a frustrated user https://github.com/hyperion-project/hyperion/issues/656
:)

**Comment by ntim** [comment]
Ok, having read various discussions, maybe a more constructive approach would be to ask "why is insanelight promoted on the website and why do they sell kits with hyperion on it" or "where do the donations go".

**Comment by tpmodding** [comment]
-.- that is another reason why we use a moderated wiki :) every troll could be change anything...

blocked him sorry, we dont need trolls or any thing. and your questions we can answer later :) we dont use donations for our holidays..we have to pay the forum/wiki/domain/server licences and costs...

**Comment by Tester0815** [comment]
LOL
You opened a new site to make business and telling, the money goes in the infrastructure ?
There were no need to make a new site, except making profit with existing code.

Wiki,domain,issue tracker were already existing before.

Making profit from a free source project is okay, but not deleting any knowhow existing like here in the wiki.
Revert the wiki pages, learn from the structure yourself.
Do you think I will contribute anything more ?
To support your business ? You can't be real.

**Comment by tpmodding** [comment]
1. we dont make any profit or business
2. before we started with everything, we asked tvdzwan -> the owner, everything is in agreement with him. so what is your problem? it is still his project! all rights are him. the domain etc is registered on his name, by HIMSELF... 
3. this wiki isnt good, as you can see if someone like you comes and starts flaming without reason...and can manipulate everything.
4. issue tracker had before we startet nearly over 350 entries...we wrote all to an to-do-list and work on it.
5. hyperion wasnt maintained for nearly 2 years, due to private reasons from tvdzwan and poljvd.
6.we doent deleted any stuff or knowhow, we transfered to the new wiki, we have local backups from everything. AND we expanded the wiki...
7. you came everytime with "you did this, you did that" but no reasonable facts! are you blind? dont you see the updates and progress since february??
8. last but not least -> it is EVERYTHING in tvdzwn's hands!!! he is still the owner, he is still the admin, it is still his project! so what? we dont stole anything or make it to OUR buisness! everything is in his hands!

if you dont want to support this, just fork it and go your own way...nobody will hold you :)

i'm done and out, have a good day!

**Comment by RickDB** [comment]
He's just a troll with a spare account, if he keeps this up he will get a Github ban pretty soon.
Constructive comments are appreciated but this isn't.

**Comment by Tester0815** [comment]
@tpmodding Did you compare the old wiki pages ????????????
Where ist the info on the new site with WS2801 Support graphics ?
The old wiki with the physical content has a straight list -> LED name -> how to connect this.
New Wiki 4 Pin - Empty Page with describing anything.

Who will get the earning from the page ads?
Who will get the donations ?
Who will get the provision of the linked shops ?

@RickDB Sorry, if you don't understand any critics about critics for going in business from an free an open project.
And then what happen with ban ppl ?
You think real troll can be stopped with a ban on github? How naive are you ?

**Comment by Fabi1080** [comment]
Hey, ive been following this project for quite some years now and i've seen development stopping and more and more issues opening. The project was basically almost dead.

Then these guys came and cleaned everything up and thought about how to structure things better, how to make everything simpler and how to improve development. Now this project is more alive then ever, every week there are new features integrated and bits and pieces improved.

If these guys wouldn't have put so much effort into the project, it would still be lying in its death bed. I bet it had cost them a lot of time and everyone profits from their doing. So why aren't they allowed to be compensated for their effort and time?

I don't know if they just make enough to pay for expenses or sit in s shit load of money and i don't care. They went into the project when no one else would, therefore they can have the revenues.

Also there are a shit ton of blogs describing how to set up hyperion, should we also point our fingers at those blaming them for making money with contributed, open source code?

**Comment by brindosch** [comment]
If we do some math and look on the bills we get (licences/server) we are still at the red area. I bet you won´t be a rich person from such a project. It is more a hope to be on a zero level.
So currently we invested very much time(!) to get the current state we are on! And also some money - our own money in something we want to contribute and improve - contributing for free is like volunteer work! 
I don´t need all that improvements for myself, but i thought it is very sad to let this great project to go to pot. (For this you need "visions", "ideas", stamina (!) and self-initiative - I am no programmer)
So i contacted tvdzwan, cause i didn´t want to fork the project.

And i think so we are on a good way.

Blogs: This is no lie, most blogs use ref ids to earn money with it. and tvdzwan/poljvd (the founder! just because of him you could use this software!) see no cent of his work, cause he had the vision to create a open source project which is free for everyone. He spend for sure much time to develope this.

I think (I/we) done much things the right way, for further develop and improvement we need "volunteers", yes. It is impossible to care just with 3 guys on one project which grows that much. I am happy with the devs and the team! All time polite and helpful.
All the parts of a successful project
