### ISSUE TITLE
v4l2 (proto forward) throws an error

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion#674]
@redPanther 
one of the PRs from 662 to 669 create always this message (forwarder disabled, proto and json server enabled)
```
QObject::connect: Cannot connect DispmanxWrapper::emitImage(int, const Image<ColorRgb>&, const int) to (null)::sendImageToProtoSlaves(int, const Image<ColorRgb>&, const int)
```
as a hint, you force this message always if you disable the proto server (for example if you install the current beta or the stable hyperion)

Thank you for investigation

**Comment by redPanther** [comment]
the target of connect is gone " to (null)", because forwarder is disabled. This line should be surounded by an condition that test if target (the forwarder) is valid. I have to search the line, bossibly other grabbers could be affected to.

this warning type is standard by qt, nothing to worry unless you intend to make this signal slot connection.

I'll have a look

**Comment by brindosch** [comment]
yes, all grabbers are affected.
and not sure why, but my kodicheck currently won´t work (it won´t shutdown the grabber - log looks good - it should shutdown)

**Comment by redPanther** [comment]
I'll investigate it this weekend, could you post your config (to be sure that I'm doing the same)

**Comment by brindosch** [comment]
yes, of course
http://pastebin.com/8eMiyQq2

**Comment by redPanther** [comment]
I'm not readed your issue properly. Sure if you disable the proto server, no proto connections can be made.

Proto is used by your configured forwarder and all grabbers.

Perhaps we can make a default for proto and json server, so we always have those servers. Congiguration is for changing the default port.

**Comment by brindosch** [comment]
Yes, or i disable the enable/disable button

But this mesage was thrown with proto enabled which should not be the case
Am 04.06.2016 9:25 vorm. schrieb "redPanther" <notifications@github.com>:

**Comment by redPanther** [comment]
as hotfix:
in hyperiond.cpp

change this:
`void startNetworkServices(const Json::Value &config, Hyperion &hyperion, JsonServer* jsonServer, ProtoServer* protoServer, BoblightServer* boblightServer) 
`
into this:
`void startNetworkServices(const Json::Value &config, Hyperion &hyperion, JsonServer* &jsonServer, ProtoServer* &protoServer, BoblightServer* &boblightServer) `

**Comment by brindosch** [comment]
Thank you for the fast fix,
but there is still a issue from 662 to 669 which leads to non working dispmanx regarding kodicheck?
Could you verify this?
Kodi check shuts down, but dispmanx don´t do it? It still grabs.

**Comment by redPanther** [comment]
I think it's the same thing. some `&` are mising ...

**Comment by brindosch** [comment]
https://github.com/hyperion-project/hyperion/pull/663/files#diff-975b84a0bb29583e8983da66c1373744R211

looks like?

ot: you corrected the space between *, this is also at other grabbers if i seen that right.

I will correct it. So i just need to add a & at the same pattern? like your fix?

**Comment by redPanther** [comment]
done a pr already

**Comment by brindosch** [comment]
*cry nothing i could do :)
Thank you very much (fast)!

**Comment by redPanther** [comment]
diff between:
myfunc( int myvar)

and
myfunc( int &myvar)

is that I can change the content of myvar in upper scope. This argument thing with an & is called "call by reference".
The first method declaration I can change myvar to, but myvar outside the methode is not changed.

This was the problem. xbmcChecker was set to "0" in upper scope. The function that creates the xbmc object, created the object very well, but xbmcChecker in upper scope was still "0" instead of the real xbmc object ... damn c++ ;-)
