### ISSUE TITLE
Feature request: HyperCon Top Gap for no LED on top (Canvas usage)

### ISSUE THREAD

**Issue by GM-Jokemaster** [hyperion-project/hyperion#798]
Hi erveryone,

I like to have a check box for no Top LED (Projector to Canvas usage).
Or a Top Gap value like Bottom Gap  :)
Hope it istn't to dificult to implement.
I have seen someon made Config right,top and left,top and in the end merged ervery thing.
Thats a very time consumig thing.
 
Kind regards and keep up the awsome work!

**Comment by RickDB** [comment]
Code wise not sure if viable but what you could try  is something hacky with the HyperCon config tool:

- Set the start offset so that it turns on the left or right side and ends at the top, then set your led count correctly to still cover the top area and note the number of the one stopping near the top leds.

Now let it generate an Hyperion json config file and edit it manually, tricky part comes now:

- In this file you have leds section which contains led IDs like so:

```
		{
			"index" : 275,
			"hscan" : { "minimum" : 0.9500, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0727, "maximum" : 0.0909 }
		},
		{
			"index" : 276,
			"hscan" : { "minimum" : 0.9500, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0545, "maximum" : 0.0727 }
		},
		{
			"index" : 277,
			"hscan" : { "minimum" : 0.9500, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0364, "maximum" : 0.0545 }
		},
		{
			"index" : 278,
			"hscan" : { "minimum" : 0.9500, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0182, "maximum" : 0.0364 }
		},
		{
			"index" : 279,
			"hscan" : { "minimum" : 0.9500, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.0182 }
		}
```

Before the we noted the LED number where we wanted to stop so now remove any indexes which are higher than that, in the above example if I wanted to stop at 267 would edit it like this:

```
		{
			"index" : 275,
			"hscan" : { "minimum" : 0.9500, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0727, "maximum" : 0.0909 }
		},
		{
			"index" : 276,
			"hscan" : { "minimum" : 0.9500, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0545, "maximum" : 0.0727 }
		}
```

Not that it can't end with a comma as that is the separator between each LED index (ID).
